<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zf2Multimedia\Module'      => __DIR__ . '/Module.php',
    'Zf2Multimedia\Image\Image' => __DIR__ . '/src/Zf2Multimedia/Image/Image.php',
);
